# nginx proxy address - http://172.17.0.1:59044

name: pihole
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: pihole/pihole:latest
    container_name: pihole-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      DNSSEC: true
      TAIL_FTL_LOG: 1
      TEMPERATUREUNIT: f
      WEBTHEME: default-dark
      WEBUIBOXEDLAYOUT: boxed
      TZ: ${TZ:-America/New_York}
      FTLCONF_dns_listeningMode: all
      FTLCONF_misc_etc_dnsmasq_d: true
      PIHOLE_DOMAIN: ${BASE_HOST_NAME:-$HOSTNAME}
      WEBPASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      FTLCONF_webserver_api_password: ${APP_ADMIN_PASS:-changeme_admin_password}
      FTLCONF_dns_upstreams: 103.124.104.139;82.29.128.43;1.1.1.1;8.8.8.8
      CONTAINER_NAME: pihole-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '172.17.0.1:59044:80/tcp'
    volumes:
      - './volumes/config/pihole:/etc/pihole'
      - './volumes/config/dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - SYS_TIME
      - SYS_NICE
      - NET_ADMIN
    networks:
      - pihole
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://pihole-app:80'
      - 'cloudflare.hostname=pihole.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.pihole-app.entrypoints=http'
      - 'traefik.http.routers.pihole-app-secure.tls=true'
      - 'traefik.http.routers.pihole-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.pihole-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.pihole-app.middlewares=pihole-app-https-redirect'
      - 'traefik.http.routers.pihole-app-secure.entrypoints=https'
      - 'traefik.http.routers.pihole-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.pihole-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.pihole-app-secure.service=pihole-app'
      - 'traefik.http.services.pihole-app.loadbalancer.server.port=80'

networks:
  pihole:
    name: pihole
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
